server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/monitor?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 10
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      filters:
        stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*

  freemarker:
    request-context-attribute: rc
    content-type: text/html
    charset: utf-8
    cache: true
    suffix: .html
    settings:
      template_update_delay: 0
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: #.###
      auto_import: /ftl/main.ftl as p

mybatis-plus:
  mapper-locations: classpath*:cn/sibetech/monitor/mapper/**/*.xml
  type-aliases-package: cn.sibetech.monitor.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl